name: Deploy project

'on':
  push:
    branches: [main]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-

      - name: Build project
        run: pnpm build

      - name: Deploy project to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount:
            '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUSES_ESTELI_D2D5E }}'
          channelId: live
          projectId: buses-esteli-d2d5e
