name: Deploy preview project

'on':
   push:
      branches: [dev]

jobs:
   build_preview:
      runs-on: ubuntu-latest

      strategy:
         matrix:
            node-version: [18.x]

      steps:
         - uses: actions/checkout@v3.1.0

         - name: Using Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v3.5.1
           with:
              node-version: ${{ matrix.node-version }}

         # Use npm to install packages due to using pnpm causes error on build.
         # Commit: #efed4d0
         - name: Install dependencies
           run: npm install

         - name: Build project
           run: npm run build

         - name: Deploy preview to Firebase
           uses: FirebaseExtended/action-hosting-deploy@v0
           with:
              repoToken: '${{ secrets.GITHUB_TOKEN }}'
              firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUSES_ESTELI_D2D5E }}'
              expires: 2d
              projectId: buses-esteli-d2d5e
              channelId: 'preview'
           env:
              FIREBASE_CLI_PREVIEWS: hostingchannels

         - name: Delete older preview runed workflows
           uses: Mattraks/delete-workflow-runs@v2.0.3
           with:
              token: ${{ secrets.GITHUB_TOKEN }}
              repository: 'Felix-Icaza/estelibuses'
              retain_days: 1
              keep_minimum_runs: 3
